//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Trabajo_2.AlumnoAsignatura {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MiWSSoap", Namespace="http://tempuri.org/")]
    public partial class MiWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GuardarAlumnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarAsigOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaralumnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarasignaturaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MiWS() {
            this.Url = global::Trabajo_2.Properties.Settings.Default.Trabajo_2_AlumnoAsignatura_MiWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GuardarAlumnCompletedEventHandler GuardarAlumnCompleted;
        
        /// <remarks/>
        public event GuardarAsigCompletedEventHandler GuardarAsigCompleted;
        
        /// <remarks/>
        public event ListaralumnoCompletedEventHandler ListaralumnoCompleted;
        
        /// <remarks/>
        public event ListarasignaturaCompletedEventHandler ListarasignaturaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarAlumn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarAlumn(string nombre, string apellidopat, string apellidomat, string email, string numeromatri) {
            object[] results = this.Invoke("GuardarAlumn", new object[] {
                        nombre,
                        apellidopat,
                        apellidomat,
                        email,
                        numeromatri});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAlumnAsync(string nombre, string apellidopat, string apellidomat, string email, string numeromatri) {
            this.GuardarAlumnAsync(nombre, apellidopat, apellidomat, email, numeromatri, null);
        }
        
        /// <remarks/>
        public void GuardarAlumnAsync(string nombre, string apellidopat, string apellidomat, string email, string numeromatri, object userState) {
            if ((this.GuardarAlumnOperationCompleted == null)) {
                this.GuardarAlumnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarAlumnOperationCompleted);
            }
            this.InvokeAsync("GuardarAlumn", new object[] {
                        nombre,
                        apellidopat,
                        apellidomat,
                        email,
                        numeromatri}, this.GuardarAlumnOperationCompleted, userState);
        }
        
        private void OnGuardarAlumnOperationCompleted(object arg) {
            if ((this.GuardarAlumnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarAlumnCompleted(this, new GuardarAlumnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuardarAsig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GuardarAsig(string nombreasig, int creditos) {
            object[] results = this.Invoke("GuardarAsig", new object[] {
                        nombreasig,
                        creditos});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarAsigAsync(string nombreasig, int creditos) {
            this.GuardarAsigAsync(nombreasig, creditos, null);
        }
        
        /// <remarks/>
        public void GuardarAsigAsync(string nombreasig, int creditos, object userState) {
            if ((this.GuardarAsigOperationCompleted == null)) {
                this.GuardarAsigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarAsigOperationCompleted);
            }
            this.InvokeAsync("GuardarAsig", new object[] {
                        nombreasig,
                        creditos}, this.GuardarAsigOperationCompleted, userState);
        }
        
        private void OnGuardarAsigOperationCompleted(object arg) {
            if ((this.GuardarAsigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarAsigCompleted(this, new GuardarAsigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listaralumno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Alumno[] Listaralumno() {
            object[] results = this.Invoke("Listaralumno", new object[0]);
            return ((Alumno[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaralumnoAsync() {
            this.ListaralumnoAsync(null);
        }
        
        /// <remarks/>
        public void ListaralumnoAsync(object userState) {
            if ((this.ListaralumnoOperationCompleted == null)) {
                this.ListaralumnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaralumnoOperationCompleted);
            }
            this.InvokeAsync("Listaralumno", new object[0], this.ListaralumnoOperationCompleted, userState);
        }
        
        private void OnListaralumnoOperationCompleted(object arg) {
            if ((this.ListaralumnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaralumnoCompleted(this, new ListaralumnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listarasignatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Asignatura[] Listarasignatura() {
            object[] results = this.Invoke("Listarasignatura", new object[0]);
            return ((Asignatura[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarasignaturaAsync() {
            this.ListarasignaturaAsync(null);
        }
        
        /// <remarks/>
        public void ListarasignaturaAsync(object userState) {
            if ((this.ListarasignaturaOperationCompleted == null)) {
                this.ListarasignaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarasignaturaOperationCompleted);
            }
            this.InvokeAsync("Listarasignatura", new object[0], this.ListarasignaturaOperationCompleted, userState);
        }
        
        private void OnListarasignaturaOperationCompleted(object arg) {
            if ((this.ListarasignaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarasignaturaCompleted(this, new ListarasignaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Alumno {
        
        private int iDAlumnoField;
        
        private string nombreField;
        
        private string apellidoPAtField;
        
        private string apellidoMatField;
        
        private string emailField;
        
        private string numeroMatriculaField;
        
        /// <remarks/>
        public int IDAlumno {
            get {
                return this.iDAlumnoField;
            }
            set {
                this.iDAlumnoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string ApellidoPAt {
            get {
                return this.apellidoPAtField;
            }
            set {
                this.apellidoPAtField = value;
            }
        }
        
        /// <remarks/>
        public string ApellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                this.apellidoMatField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroMatricula {
            get {
                return this.numeroMatriculaField;
            }
            set {
                this.numeroMatriculaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Asignatura {
        
        private int iDAsignaturaField;
        
        private string nombreAsignaturaField;
        
        private int creditosField;
        
        /// <remarks/>
        public int IDAsignatura {
            get {
                return this.iDAsignaturaField;
            }
            set {
                this.iDAsignaturaField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAsignatura {
            get {
                return this.nombreAsignaturaField;
            }
            set {
                this.nombreAsignaturaField = value;
            }
        }
        
        /// <remarks/>
        public int Creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GuardarAlumnCompletedEventHandler(object sender, GuardarAlumnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarAlumnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarAlumnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GuardarAsigCompletedEventHandler(object sender, GuardarAsigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarAsigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarAsigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListaralumnoCompletedEventHandler(object sender, ListaralumnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaralumnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaralumnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Alumno[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Alumno[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListarasignaturaCompletedEventHandler(object sender, ListarasignaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarasignaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarasignaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Asignatura[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Asignatura[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591